name: flutterxy
description: Flutter project based on Vuexy template


publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/dashboard/
